title: "Lacoste — Esami PoliTO"
description: "Materiale ed esercitazioni — Politecnico di Torino"
theme: jekyll-theme-cayman

# Menu di navigazione in alto
plugins:
  - jekyll-relative-links

markdown: kramdown
